# run the testsuite on travis-ci.com
---
# versions to run on
env:
  - PG_SUPPORTED_VERSIONS=9.5
  - PG_SUPPORTED_VERSIONS=9.6
  - PG_SUPPORTED_VERSIONS=10
  - PG_SUPPORTED_VERSIONS=11
  - PG_SUPPORTED_VERSIONS=12
  - PG_SUPPORTED_VERSIONS=13

language: C
dist: bionic
sudo: required

install:
  # upgrade to get newer apt.pg.o.sh file
  - sudo apt-get update
  - sudo apt-get install -y postgresql-common fakeroot
  # install required PostgreSQL packages (purging the existing installation first)
  - sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -v $PG_SUPPORTED_VERSIONS -p -i
  - sudo apt-get build-dep -y .

script:
  - pg_buildext updatecontrol
  - dpkg-buildpackage -us -uc -rfakeroot -b
  - for deb in ../*.deb; do echo "$deb:"; dpkg-deb --info $deb; dpkg-deb --contents $deb; done
  - sudo dpkg -i ../*.deb
  - pg_buildext -i '--locale=C.UTF-8' installcheck
